name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          cd scripts
          python trainRegressor.py
          cd ..
          cat random-forest-metrics.txt >> report.md
          cml-publish random-forest-result.png --md >> report.md
          cml-publish random-forest-feat-importance.png --md >> report.md
          cml-send-comment report.md
